
echo %IP%	i1.ytimg.com #HAC>>%windir%\System32\drivers\etc\hosts
echo %IP%	i2.ytimg.com #HAC>>%windir%\System32\drivers\etc\hosts
echo %IP%	i3.ytimg.com #HAC>>%windir%\System32\drivers\etc\hosts
echo %IP%	i4.ytimg.com #HAC>>%windir%\System32\drivers\etc\hosts

echo %IP%	youtu.be #HAC>>%windir%\System32\drivers\etc\hosts
echo %IP%	ytimg.l.google.com #HAC>>%windir%\System32\drivers\etc\hosts
echo %IP%	i.ytimg.com #HAC>>%windir%\System32\drivers\etc\hosts

echo %IP%	v1.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.cache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.cache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.cache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.cache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.cache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.cache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.cache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.cache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v1.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v2.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v3.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v4.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v5.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v6.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v7.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v8.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v9.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v10.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v11.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v12.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v13.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v14.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v15.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v16.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v17.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v18.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v19.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v20.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v21.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v22.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v23.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.lscache1.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.lscache2.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.lscache3.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.lscache4.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.lscache5.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.lscache6.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.lscache7.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
echo %IP%	v24.lscache8.c.bigcache.googleapis.com #HAC >>%windir%\System32\drivers\etc\hosts
